name: Genie Cloud Bridge
slug: genie
version: "1.0.0"
description: Genie hardware cloud bridge
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386

host_network: true
hassio_api: true

options:
  email: ""
  password: ""
  device_id: ""

schema:
  email: str
  password: password
  device_id: str
